// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqluuzaW9mhAQnBn2j95kMYoC4eIkl_9c',
    appId: '1:588146814653:web:4d3a14f58aca89c8a991d4',
    messagingSenderId: '588146814653',
    projectId: 'corkapp-dev',
    authDomain: 'corkapp-dev.firebaseapp.com',
    storageBucket: 'corkapp-dev.appspot.com',
    measurementId: 'G-Q2MVX9YYHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrRsG5gfC77IsIue5Enx-pMuiSyjaEn4o',
    appId: '1:588146814653:android:c66c724a01d3383ca991d4',
    messagingSenderId: '588146814653',
    projectId: 'corkapp-dev',
    storageBucket: 'corkapp-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS6fmvfzpfR87wv4BxyjF4Wjun6lTs1NQ',
    appId: '1:588146814653:ios:976e4c0946e4a25aa991d4',
    messagingSenderId: '588146814653',
    projectId: 'corkapp-dev',
    storageBucket: 'corkapp-dev.appspot.com',
    androidClientId: '588146814653-007octogfqhcdp4relfn1h53kifh4v3b.apps.googleusercontent.com',
    iosClientId: '588146814653-g1isclmjmtl8j66f5jq9p672onb1hc9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS6fmvfzpfR87wv4BxyjF4Wjun6lTs1NQ',
    appId: '1:588146814653:ios:976e4c0946e4a25aa991d4',
    messagingSenderId: '588146814653',
    projectId: 'corkapp-dev',
    storageBucket: 'corkapp-dev.appspot.com',
    androidClientId: '588146814653-007octogfqhcdp4relfn1h53kifh4v3b.apps.googleusercontent.com',
    iosClientId: '588146814653-g1isclmjmtl8j66f5jq9p672onb1hc9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseLogin',
  );
}
